<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

print(a)
print(a.ndim, a.shape)
print(b)
print(b.ndim, b.shape)

[[0.88809165 0.80933556 0.69517981 ... 0.78687589 0.82007836 0.69311413]
 [0.66299843 0.94268316 0.18203767 ... 0.98083919 0.64720451 0.73443126]
 [0.40227343 0.06416691 0.00573907 ... 0.97814839 0.4382885  0.48329427]
 ...
 [0.0617475  0.21967194 0.83607061 ... 0.92394507 0.26871196 0.54915267]
 [0.16801304 0.59662731 0.64441546 ... 0.30545398 0.85212444 0.98147347]
 [0.29552853 0.4924888  0.94694845 ... 0.41296777 0.34686606 0.78267987]]
2 (100, 100)
[[0.93969705 0.76433739 0.14172619 ... 0.59357202 0.85236926 0.05624859]
 [0.04507093 0.07905672 0.95360382 ... 0.60316577 0.09375439 0.92887752]
 [0.6397242  0.58562993 0.97206456 ... 0.94237772 0.67572899 0.37559828]
 ...
 [0.0621377  0.45779113 0.08534852 ... 0.58756965 0.49423483 0.91874665]
 [0.62658976 0.93189411 0.08248675 ... 0.98905532 0.2769535  0.86896495]
 [0.23705616 0.35632173 0.48611647 ... 0.7360786  0.75671476 0.46547295]]
2 (100, 100)


In [3]:
a_list = list(a)
a_list = [list(i) for i in a_list]
b_list = list(b)
b_list = [list(i) for i in b_list]

In [4]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = []
    for i in range(len(a)):
        d = []
        for j in range(len(a[0])):
            d.append(sum([n * m for n, m in zip(a[i], list(zip(*b))[j])])) 
            # list(zip(*b)) - аналог транспонирования матрицы, поэтому перемножаем не строка*столбец, а две строки
            # Он дает список кортежей, в этом случае это подходит
            # Но если бы был нужен список списков,то нужно было бы использовать list(map(list, zip(*b)))
        c.append(d)    
    return c    

In [5]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return np.dot(a, b)

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a_list, b_list)

Wall time: 948 ms


In [7]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 38.1 ms


In [8]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.7209345060109627e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [9]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.41874257 0.50680329 0.8279572 ] [0.69281483 0.12886331 0.14287948]


In [10]:
def scalar_product(a,b):
    #YOUR CODE
    return sum(n * m for n, m in zip(a, b))

In [11]:
def np_scalar_product(a,b):
    #YOUR CODE
    return np.dot(a, b)

In [12]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 0 ns


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [13]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    #YOUR CODE
    diag = np.diagonal(a, offset=0, axis1=0, axis2=1)
    return diag[diag % 2 == 0].sum()

In [14]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 6, 5, 6, 3],
       [3, 6, 2, 2, 7],
       [9, 5, 8, 1, 3],
       [8, 5, 9, 4, 2],
       [6, 1, 1, 4, 4]])

In [15]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 1.03 ms


24

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


​

​ 

In [16]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    #param A: np.array[m,n]
    #YOUR CODE

    result = np.cumsum(A, axis=1)
    return result

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [19]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    #YOUR CODE
    Y = X.copy()
    Y[:, 1::2] = a
    Y[:, 0::2] **= 3
    Y = Y[:, ::-1]
    
    return np.hstack((X, Y))

In [20]:
X = np.array([[1,2,3,4,5],[1,2,3,4,5]])
np_transformation(X)

array([[  1,   2,   3,   4,   5, 125,   1,  27,   1,   1],
       [  1,   2,   3,   4,   5, 125,   1,  27,   1,   1]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [23]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [24]:
diff = np.diff(X)  # array - разница между соседними элементами
diff

array([ 1,  0,  1,  0, -2,  0,  4,  0, -3,  1,  0])

In [25]:
np.where(diff != 0)

(array([0, 2, 4, 6, 8, 9], dtype=int64),)

In [26]:
result = list(*np.where(diff != 0))  # индексы соседних элементов, которые различны
result = np.array(result)
result += 1 # сдвиг вправо для корректного деления по индексам
result

array([ 1,  3,  5,  7,  9, 10], dtype=int64)

In [27]:
np.split(X, result)

[array([1]),
 array([2, 2]),
 array([3, 3]),
 array([1, 1]),
 array([5, 5]),
 array([2]),
 array([3, 3])]

In [28]:
unique,  counts = np.unique(np.array([5, 5]), return_counts=True)
print(unique)
print(counts)

[5]
[2]


In [29]:
# функция, решающая задачу с помощью NumPy

def np_encode(a):
    #YOUR CODE
    diff = np.diff(a) # array - разница между соседними элементами
    result = list(*np.where(diff != 0)) # индексы соседних элементов, которые различны
    result = np.array(result)
    result += 1 # сдвиг вправо для корректного деления по индексам
    
    elem_list, count_list = [], []
    
    for i in np.split(a, result):
        unique, counts = np.unique(i, return_counts=True)
        elem_list.append(*unique)
        count_list.append(*counts)
    return (np.array(elem_list), np.array(count_list))    

In [30]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

Wall time: 0 ns


In [31]:
x

array([1, 2, 3, 1, 5, 2, 3])

In [32]:
num

array([1, 2, 2, 2, 2, 1, 2], dtype=int64)